# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18962621f7e808fe233b5ae0c00ca7ce3050d51fa277122bb64f65956dc14aa08cc328a1a83f44a56142e6859aee96a2ba6c4bf75c9e4f4d9a82ca10d4e6f8d4

test:
  secret_key_base: 3e433feff5a9b05f77a54d7b1b6a43616b1065b8f3995b6c1e1bb045859f09d476192aa3975463c5781e3edd5eac4dc6de7d4e5ccf15157995f7722507898104

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
